### ISSUE TITLE
Display correct CTR/FIR boundaries

### ISSUE THREAD

**Issue by spiox123** [maiuswong/simaware-express#10]
Is there a possibility to display the correct CTR/FIR boundaries on the map like on VATspy or other clients which use the [vatspy data project](https://github.com/vatsimnetwork/vatspy-data-project) from github? This would help much CTR controllers that pilot will not contact them because of Simaware showing the wrong boundaries (for example no split from LSAG_CTR and LSAZ_CTR). Thanks for checking this!

**Comment by SwietyMik** [comment]
@maiuswong Hello. Simaware already displays the correct boundaries for individual LON_**_CTRs, and @spiox123 it would just be a case of adding/editing the polygons to match up with what you think they should be.
Following questions regarding https://github.com/maiuswong/simaware-express/blob/9e75142f0ac94bb0935c8c7c5dc10e9c70eb4d4a/public/livedata/firboundaries.json
Would it be possible for me to update the `EGTL` polygons and split the London TMA to each individual sector, given that it works for LON_C_CTR and more?
Could you explain how for example `EGTT-SC` has a label of LON_SC_CTR on the map, and were are they "linked" to eachother. Unlike the TRACON boundaries, there is no string to bind the `prefix` to the name. I am not to "code-minded" with these things so please spare me if I'm using the wrong terminology :)
