### ISSUE TITLE
Map occassionally does not load

### ISSUE THREAD

**Issue by kenkam** [maiuswong/simaware-express#100]
Sometimes variables are not available on initial load, because it is trying to access a variable that hasn't been initialized in an async method.

![image](https://github.com/maiuswong/simaware-express/assets/121124/ac5814e5-46ba-4fb5-9417-2f4b244d2a5c)

#99 Fixes this

**Comment by maiuswong** [comment]
Merged

**Comment by kenkam** [comment]
This has triggered #103, which is fixed in #104.

**Comment by kenkam** [comment]
@maiuswong I think fixing the `awaits` has made #103 appear, which is fixed in #104.
