### ISSUE TITLE
Layers not working because of definitions

### ISSUE THREAD

**Issue by ardayasar** [maiuswong/simaware-express#103]
Tried to reach website and couldn't see ATC layers. The problem has been from layers_positions. Couldn't assign because it was not declared before

Uncaught (in promise) ReferenceError: layers_positions is not defined
    findLayersPosition https://simaware.ca/js/simaware_app/app.js:1
    refreshATC https://simaware.ca/js/simaware_app/app.js:1
    each jQuery
    refreshATC https://simaware.ca/js/simaware_app/app.js:1

**Comment by kenkam** [comment]
Fixed in https://github.com/maiuswong/simaware-express/pull/104

**Comment by maiuswong** [comment]
Thanks @kenkam!
