### ISSUE TITLE
Hide cancelled events on the map

### ISSUE THREAD

**Issue by MardilB** [maiuswong/simaware-express#12]
When future events are cancelled / deleted from the VATUSA forums or other event data sources, they continue to be shown on the SimAware map.  This is a problem because pilots may plan to participate in the cancelled event or waste time searching for details on an event that is only shown in SimAware.

**Expected behavior**
Events should no longer appear on the SimAware map if they are cancelled / deleted from the source events site at least one day before the event is scheduled to start.

**Additional details**
Here are two current examples of this pulled from https://api2.simaware.ca/api/livedata/events.json:
<details>
<summary>Click to expand</summary>
{"id":875,"myvatsim_id":4416,"created_at":"2022-02-23 00:00:15","updated_at":"2022-02-23 00:00:15",
"name":"Don't Bust the Bravo!","start":"2022-04-09 23:00:00","end":"2022-04-10 03:00:00","airports":"KISM,KSFB,KMLB,KORL","description":"<p>Looking for a challenge this weekend? Come fly down in the South of the US with us! The only requirement? Remain clear of the Orlando Class Bravo! We are going to be staffing up our smaller airports inside the F11 TRACON for your VFR enjoyment, but remember, Don't Bust the Bravo!<\/p><br>"},

{"id":632,"myvatsim_id":4165,"created_at":"2022-01-22 00:00:15","updated_at":"2022-01-22 00:00:15","name":"Lounging? In the Lowcountry","start":"2022-04-09 23:00:00","end":"2022-04-10 03:00:00","airports":"KMYR,KSAV,KCAE","description":"<p>Ever want to see the famous Southern Hospitality that everyone is always talking about? Well here is your chance! Come join the Virtual Jacksonville ARTCC as we staff up the major airports around the Lowcountry and provide you with some fabulous Southern ATC, as you fly into, out of and around the Lowcountry! Bring your jets, props and pistons and feel free to fly fly all around VFR as we present you with Lounging? In the Lowcountry!<\/p><br>"},
</details>

**Comment by maiuswong** [comment]
Fixed some time ago on the backend.
