### ISSUE TITLE
Pilots with IR show up as CMEL

### ISSUE THREAD

**Issue by bruceyang1998** [maiuswong/simaware-express#15]
![image](https://user-images.githubusercontent.com/9063679/163074240-30de58af-7f99-4236-a1e7-0edaa55e6fd0.png)
![image](https://user-images.githubusercontent.com/9063679/163074247-283fd5a9-68ef-4b89-a367-99ebc8a9a9e7.png)

**Comment by bruceyang1998** [comment]
![image](https://user-images.githubusercontent.com/9063679/163074349-d8f94895-d081-4d56-8578-16ab23c290ed.png)
![image](https://user-images.githubusercontent.com/9063679/163074360-84aa3bb8-ec33-4094-8d8c-eb16c63ffb6a.png)
![image](https://user-images.githubusercontent.com/9063679/163074380-5f7193d3-8a82-4436-b6ce-b23324cdc15d.png)
![image](https://user-images.githubusercontent.com/9063679/163074397-15b6393c-6c6d-4381-90a6-1bf48670e9b7.png)

**Comment by maiuswong** [comment]
Data update resolved this issue.
