### ISSUE TITLE
SBWH_APP is not showing on map

### ISSUE THREAD

**Issue by Victor237Mendes** [maiuswong/simaware-express#16]
![image](https://user-images.githubusercontent.com/69435354/168404773-4254dcf3-ef6e-4c92-8409-3d8116c84099.png)
![image](https://user-images.githubusercontent.com/69435354/168404779-26cad082-c40c-43d0-9ec6-c616d2bb3aa2.png)

**Comment by bruceyang1998** [comment]
Can be added to simaware through https://github.com/maiuswong/simaware-tracon-project
