### ISSUE TITLE
[Request] Filters for airport arrivals/departures

### ISSUE THREAD

**Issue by crowmium** [maiuswong/simaware-express#17]
Per title, it would be awesome to be able to filter departures OR arrivals for a specific airport. This would allow people doing traffic management to see the traffic load into or out of a specific field. Often arrival capacity is the limiting factor for an airport, but the traffic picture can be somewhat confusing when looking at departures and arrivals simultaneously.

Another nice filter would be for airport pairs to see the traffic flowing specifically to and from those two airports at any given time.

I imagine either of these features could be implemented via the search bar or GUI, whichever is easiest.

**Comment by maiuswong** [comment]
Implemented in 80223322
