### ISSUE TITLE
Invalid response from KBTR

### ISSUE THREAD

**Issue by nocarryr** [maiuswong/simaware-express#19]
At the time of creating this issue, I am seeing exceptions thrown from the `refreshATC` function call which block the reset of js initialization.

It seems to be coming from an invalid response from one or more LatLong requests in the following bit of code:

https://github.com/maiuswong/simaware-express/blob/6bf91a99575ac949dcd6149188e707f0626cc0a6/public/js/simaware_app/simaware-map.js#L976-L989

The `local` object in question contains the ICAO code in the "lat" key:
```javascript
{"loc":{"icao":"BTR","iata":"United States","name":"Baton Rouge Metropolitan","city":" Ryan Field, Baton Rouge","lat":"\\"KBTR\\"","lon":"30.53319931","callsign":""},"GND":[{"callsign":"BTR_GND","name":"Jude Adams ","freq":"121.900","atis":null,"created_at_timestamp":1658448088}],"TWR":[{"callsign":"BTR_TWR","name":"Jason Lu","freq":"118.450","atis":null,"created_at_timestamp":1658448190}],"DEL":[{"callsign":"BTR_DEL","name":"Chris Vahlkamp","freq":"119.400","atis":null,"created_at_timestamp":1658451074}]}
```

And the results in `lat` being assigned as `NaN` (line 980)

I don't really have any suggestions on a solution since I'm not familiar with your codebase.  Just wanted to report while I'm waiting to redownload MSFS after yet another messed up update  :angry:

Anyway, thanks for making this great project!

**Comment by maiuswong** [comment]
Interesting.  Thanks for the report (and sorry for the late response)!
