### ISSUE TITLE
Palomar Airport Incorrect Geographical Location

### ISSUE THREAD

**Issue by jackgrenda1** [maiuswong/simaware-express#21]
McClellan-Palomar Airport (KCRQ) is located in northern San Diego, CA, U.S.A. When controlling CRQ_TWR, a controller is instead shown online at the Caravelas Airport in Southern Brazil. ATIS is displayed at the correct location, but the location of the tower controller is not.
![simawarebrazil](https://user-images.githubusercontent.com/110656947/183017980-8fb7ef88-2e87-4a1a-9760-e8f09497957e.png)

**Comment by maiuswong** [comment]
Resolved in 675c6c3.
