### ISSUE TITLE
[Question] ATC Logon Codes

### ISSUE THREAD

**Issue by Frenkii** [maiuswong/simaware-express#25]
Hey,

for EDGG we changed the logon codes to comply with sector names irl.
for example we changed EDGG_K_CTR to EDGG_KTG_CTR. When we overtake a station the new controller logs in with EDGG_K1G_CTR.

Now my questions:
- Do you use the vatspy-data for boundaries display?
- If yes, what do you prefer how we provide the new sector data.

If you use vatspy-data-project, take a look to our latest PR: https://github.com/vatsimnetwork/vatspy-data-project/pull/586

**Comment by maiuswong** [comment]
Sorry for the late reply.  SimAware uses the https://github.com/vatsimnetwork/vatspy-data-project/ and is pulled automatically each night.
