### ISSUE TITLE
SAW airport is in the wrong location

### ISSUE THREAD

**Issue by Lulsgate** [maiuswong/simaware-express#27]
![SAW](https://user-images.githubusercontent.com/115547459/195073669-cc15d4cb-450d-4ac3-b18e-b0587b06093e.jpg)

SAW/LTFJ airport is in the wrong location on your map.

Apart from this issue, SimAware is AWESOME!

Cheers
Ryan

**Comment by maiuswong** [comment]
Thank you, I will update the latlon.
