### ISSUE TITLE
Max zoom level in event page

### ISSUE THREAD

**Issue by NelisV** [maiuswong/simaware-express#3]
Since the release last night, the max zoom level in event overviews is reduced. Is this intended? I liked the previous setting. 
https://simaware.ca/event/276

**Comment by maiuswong** [comment]
It isn't - used setMaxZoom so that it wouldn't zoom in all the way on single-airport events.   Will change.

**Comment by maiuswong** [comment]
48a5860
a42fae0

Removed zoom limit

**Comment by NelisV** [comment]
Perfect, thanks!
