### ISSUE TITLE
Prefix array in TRACONBoundaries.geojson 

### ISSUE THREAD

**Issue by psvatpac** [maiuswong/simaware-express#31]
The prefix entry 
{"id":"YSSY","name":"Sydney Approach North","prefix":["SY","SY-D","SY-DE","SY-S"]
only displays one of the logins when multiple  are active. For example SY_APP, SY-D_APP and SY-DE_APP were all active, but only SY-D_APP was displayed in the simaware map.

I may have misunderstood the use of the Prefix array, but I thought it was to define multiple prefixes that shared the same boundary and assumed  that any active logins that matched the prefixes would be displayed when hovering over YSSY (in this case)

Is this the case or should I define separate entries for each callsign that shares the same boundary?

**Comment by psvatpac** [comment]
Bump. Any update of this?

**Comment by maiuswong** [comment]
Sorry for the very late reply.  My guess is that if the prefix is shortened just to "prefix":["SY"] that may actually work.
