### ISSUE TITLE
Request: history line toggle

### ISSUE THREAD

**Issue by MatisseBE** [maiuswong/simaware-express#36]
Hi

Personally, I am not a fan of the website zooming in/out when selecting a flight. It also hides all other aircraft while doing so.
Could it possibly be considered to simply show the history trail without moving the screen or hiding aircraft? Kinda like how selecting a flight in FR24 works.

-Matisse

**Comment by maiuswong** [comment]
Completed as of fe28d17.  Will look into adding flags where it makes appropriate sense to zoom.
