### ISSUE TITLE
Request: New icon for small airplanes (GA)

### ISSUE THREAD

**Issue by gabrielsaints** [maiuswong/simaware-express#37]
Create a new icon to identify the smallest airplanes (like Cessnas, Pipers, and B350). Currently, there's no easy visual way to identify.

**Comment by gabrielsaints** [comment]
it will be great if we add helicopters as well

**Comment by maiuswong** [comment]
If you can provide them, I will add them

**Comment by gabrielsaints** [comment]
> If you can provide them, I will add them

Awesome!

**Comment by berniecase** [comment]
Would this work? I'm sending this through as full size and will let you adjust as needed down to an appropriate size.

Source: https://www.iconspng.com/image/116366/topdown-airplane-view

![GA](https://github.com/maiuswong/simaware-express/assets/32081430/b4fe2d2b-c66d-4a2e-8308-c4cce1c49bf9)

**Comment by D0m1nu2** [comment]
> Create a new icon to identify the smallest airplanes (like Cessnas, Pipers, and B350). Currently, there's no easy visual way to identify.

Hey, I made a little sheet for icons where you can request them from me to make, if you could add those into there it'd be eaisier for me to keep track. :)
https://docs.google.com/spreadsheets/d/19PuA65CPhafpgc5kGOlZIQAuK-KyZl6Tp8O8KUu8OqI/edit?usp=sharing, do not share this link anywhere please and try to keep it tidy 😄
