### ISSUE TITLE
SimAware Event Analysis Request for Events over 8 hours

### ISSUE THREAD

**Issue by miguelalbano** [maiuswong/simaware-express#38]
Apologies if this is being asked in the wrong place.

Though I understand why there is a time limit for event analysis, we do have a few events that span for over 8 hours.

We had a long haul event yesterday from FACT to OMDB with departures starting around 0800z and arrivals reaching 2100z (if I'm not mistaken).

Not sure how best to suggest an option for those events to be included/added/suggested to the SimAware Events.

**Comment by maiuswong** [comment]
Hi,

The event analysis counts all flights (regardless of length) that arrive at an airport within the specified time slot.  In this case, it would be best to request an event around the time when aircraft were arriving at OMDB.  For example, if peak arrivals at OMDB were at 2100z, you could request an event between 1900 and 2300z.
