### ISSUE TITLE
VTBS/BKK wrong location in map

### ISSUE THREAD

**Issue by romtam** [maiuswong/simaware-express#44]
Hi there, 

VTBS has the wrong location on the Simaware map. Not sure where else to report this issue.

![firefox_NGNacquRyJ](https://user-images.githubusercontent.com/46883291/236634661-18b3b01d-64ae-4334-8a9d-304953beb187.png)

**Comment by maiuswong** [comment]
SimAware now syncs latlon's with the vatspy-data-project.
