### ISSUE TITLE
The name of airport ZSWZ on Simaware is not correct

### ISSUE THREAD

**Issue by jerrykam242** [maiuswong/simaware-express#45]
ZSWZ have already changed it name from Wenzhou Yongqiang Airport to Wenzhou Longwan Airport in the year of 2013. Would you please help to change the name of ZSWZ airport into it's correct and new name? Thanks a lot for your help.

With the wikipedia page of ZSWZ:https://en.wikipedia.org/wiki/Wenzhou_Longwan_International_Airport

**Comment by maiuswong** [comment]
Resolved in ccf86c2.
