### ISSUE TITLE
Request: New icons for Military Planes on Simaware map

### ISSUE THREAD

**Issue by k7d2** [maiuswong/simaware-express#51]
Hi

I have noticed nice improvements to the Simaware map when Flying on Vatsim.
The F22 now has an aircraft object showing on the map. would it be possible to do this for the following military aircraft?

F18, F15, F16. Lockheed U2 & SR71

many thanks
![F18](https://github.com/maiuswong/simaware-express/assets/139381597/1f257fb6-1053-483b-81c2-dde76c76bd7c)
anks

![F15](https://github.com/maiuswong/simaware-express/assets/139381597/2c4997c0-cf28-47ed-88fb-f7c96cc7ec15)
![Lockheed SR71](https://github.com/maiuswong/simaware-express/assets/139381597/7c7211dc-36a8-45f1-9678-4744961e64d1)

![F16](https://github.com/maiuswong/simaware-express/assets/139381597/6b98c586-6bbb-44f9-863a-391623ba5f91)
![Lockheed U2](https://github.com/maiuswong/simaware-express/assets/139381597/60b946b3-533e-4f30-a881-1f3a03c24bf4)

**Comment by D0m1nu2** [comment]
Hey, I made a little sheet for icons where you can request them from me to make, if you could add those into there it'd be eaisier for me to keep track. :)
https://docs.google.com/spreadsheets/d/19PuA65CPhafpgc5kGOlZIQAuK-KyZl6Tp8O8KUu8OqI/edit?usp=sharing, do not share this link anywhere please and try to keep it tidy 😄

**Comment by k7d2** [comment]
Hi

I forgot to add one last request for the Bae Hawk when you have time to maybe make an icon for the SimAware map.


![Hawk](https://github.com/maiuswong/simaware-express/assets/139381597/d73066a5-f4e8-47d7-8032-c0e8627ff4a4)


Many thanks

the F18 looks really good.

**Comment by maiuswong** [comment]
Multiple ac added by @D0m1nu2
