### ISSUE TITLE
IWA_TWR shows at UUBI instead of KIWA on the map

### ISSUE THREAD

**Issue by j14a** [maiuswong/simaware-express#57]
IWA_TWR is tower of Phoenix-Mesa Gateway General Airport (ICAO: KIWA, IATA: AZA) in Arizona, USA. Whenever this controller comes online, the map shows his location as Ivanovo-South airport in Russia (ICAO: UUBI, IATA: IWA). The mistake was most likely caused by the fact that "IWA", which is FAA LID for KIWA, also happens to be IATA code for Ivanovo-South. I contacted controller via chat and he confirmed he is controlling Phoenix-Mesa Gateway and not Ivanovo-South.
IWA_TWR needs to be changed its location to KIWA (33.307778, -111.655556) instead of UUBI.

![IWA-UUBI](https://github.com/maiuswong/simaware-express/assets/64866837/a50f785d-a3c2-4832-a3fc-f1ae3f07b787)

**Comment by maiuswong** [comment]
Resolved in fe28d17.
