### ISSUE TITLE
Datafeed enters arrival field on departure.

### ISSUE THREAD

**Issue by JoshuaMicallefYBSU** [maiuswong/simaware-express#60]
Hello! I am working on a site that uses this API (which is absolutley wonderful)

Had a few instances where the live.json file enters the 'arrived_at' time immediatley after departure. For context, I am still airbourne and the flight is 2.5hrs long.

![image](https://github.com/maiuswong/simaware-express/assets/91457812/78c2f806-1c85-4e62-ac9c-bcff0be7a452)
Not exactly sure why or how this is happening. However I do need the arrived_at variable to be correct to ensure my schedule site works as expected.

Any ideas/solutions would be appreciated!

**Comment by maiuswong** [comment]
Hmm, the VATSIM datafeed API should really be used for this purpose.  It's not maintained for public use and can change at any time.
