### ISSUE TITLE
Anti-meridian bug

### ISSUE THREAD

**Issue by barf** [maiuswong/simaware-express#65]
Hello
There is an issue showing the map when it is centered on or near the anti-meridian (+/- 180 degrees longitude) -- only half of the map is shown
Thanks

**Comment by maiuswong** [comment]
Not able to reproduce this issue.  May be a Leaflet limitation.

**Comment by barf** [comment]
To reproduce pan the map to the anti-meridian. This is a show-stopping bug for Pacific flights because the flight will disappear when crossing 180 longitude. Appears to have documented fixes: https://github.com/briannaAndCo/Leaflet.Antimeridian
![image](https://github.com/maiuswong/simaware-express/assets/584684/e4d6c5d5-e41d-4203-aedd-4769ea00b4c8)

**Comment by barf** [comment]
hi @maiuswong please can this be looked at? anti-meridian bugs appear solved upstream in Leaflet, and the other VATSIM maps like VATTASTIC do not have this issue
