### ISSUE TITLE
Incorrect placement of location dot

### ISSUE THREAD

**Issue by MatisseBE** [maiuswong/simaware-express#7]
Maybe this has something to do with east/west of the Meridian but these red dots, which I assume depict airport location, are placed incorrectly. Instead of right of the ICAO airport name, they should be at the left top, like the arrow. 

Maybe it isn't supposed to show the location and acts as a mere "notification" dot, either way, it got me all confused.

Location shown here is around Belgium, Netherlands, Germany,...

![image](https://user-images.githubusercontent.com/51272243/150689280-6584e72f-c56a-4011-9196-392df5c1963a.png)

Regards

**Comment by maiuswong** [comment]
That's not a location dot.  It denotes that there is a scheduled event within the next 14 days.

**Comment by erikquinn** [comment]
There are quite a lot of dots though-- on a separate note, perhaps a shorter time period would be prudent? Like 2 days, or even just "next 24 hours". Realistically, when looking for places to fly, 99% of people will be looking for event airports in the next literal 1 hour, so a 14 day event indicator seems less helpful than a 24-hour one, in my opinion. 🤷‍♂️
