### ISSUE TITLE
Confusing event time indication

### ISSUE THREAD

**Issue by Fry2412** [maiuswong/simaware-express#75]
Hi everyone,

First of all, I find the new map update very successful and clear. However, I noticed a discrepancy in the event times in the new event information at the bottom left of the screen.  
  
In the display at the respective airports it is shown correctly in zulu, whereas the display at the bottom left in my case (CET time zone) shows the local time but implies UTC/zulu time  
> In my example screenshot, the `BERlin Thuesday` event on Dec. 19 is to be considered.  

I use the latest Brave Brower `v 1.61.104`

Best regards  
  

![image](https://github.com/maiuswong/simaware-express/assets/7856444/30eb4ecd-f6c6-492f-aac5-ac8801d1107b)

**Comment by maiuswong** [comment]
Resolved in 379f6e767fdc9c05d6abb9a7a2da1cf2268140e4
