### ISSUE TITLE
Streaming overlay

### ISSUE THREAD

**Issue by Jannis-D** [maiuswong/simaware-express#8]
It would be great to have the streamer's widget from the legacy version to use as a browser source.

**Comment by MatisseBE** [comment]
Adding to this, if there's too many streamers at once, the streamers' overlay from the website itself isn't scrollable so you can't see everyone. 

I'm talking about the list shown below:
![image](https://user-images.githubusercontent.com/51272243/157042429-3095d153-f131-4f7a-9741-dba71ad73bfd.png)

**Comment by Jannis-D** [comment]
> Adding to this, if there's too many streamers at once, the streamers' overlay from the website itself isn't scrollable so you can't see everyone.
> 
> I'm talking about the list shown below: ![image](https://user-images.githubusercontent.com/51272243/157042429-3095d153-f131-4f7a-9741-dba71ad73bfd.png)

Hi, I'm not talking about this. I would suggest to open another issue for this.
