### ISSUE TITLE
Event seems to be displaying wrong date in UI

### ISSUE THREAD

**Issue by kengreim** [maiuswong/simaware-express#84]
This event is showing as Jan 1 0300-0600Z on the front end: 
![image](https://github.com/maiuswong/simaware-express/assets/34892440/dffaa423-687c-42e0-ad36-7cc82484fe0e)

The MyVATSIM events API has the start time as Jan 2 0300Z:
![image](https://github.com/maiuswong/simaware-express/assets/34892440/88f3d597-a401-45df-a8af-5236593ee2c0)

The SimAware backend also has the start time as Jan 2 0300Z (converting the UNIX time below to Zulu):
![image](https://github.com/maiuswong/simaware-express/assets/34892440/a448c6ff-3f96-497d-8745-9ee88d8e2694)

So I think this issue is either in `loadUpcomingEvents()` or more likely just in the front-end presentation [here](https://github.com/maiuswong/simaware-express/blob/a7f15a5960c4110eb4ee76fcff3e116842f9b6f2/src/js/simaware_app/simaware-infobar.js#L98C25-L98C25)? I can do some more debugging if needed.

**Comment by maiuswong** [comment]
Resolved in 4992d1e8c75438d2e2c789d3b1098fd964befa5f
