### ISSUE TITLE
No controlls on mobile

### ISSUE THREAD

**Issue by DominikTV** [maiuswong/simaware-express#85]
When on a phone/mobile view, the controlls to toggle ATC etc. not being shown.

![Screenshot_20231227-205641](https://github.com/maiuswong/simaware-express/assets/7671638/b20c0487-f067-4dba-8da7-5a7488ca2ba9)

**Comment by benediktask** [comment]
I concur. Doesn't help turning "Desktop site" on, too.

**Comment by bencodes07** [comment]
+1
iPhone 12, iOS 17.1.2, using Safari and Chrome does not work
However when I am using the Arc browser on mobile it works.

**Comment by maiuswong** [comment]
Weird because this doesn't show up when I am in responsive mode.  A workaround for now is just to drag from the menu bar (at the top) down, which will reveal the menu.

**Comment by maiuswong** [comment]
@DominikTV @bencodes07 @benediktask please test on your respective devices and report back

**Comment by benediktask** [comment]
Works now!

**Comment by bencodes07** [comment]
Nice, works for me too!

**Comment by maiuswong** [comment]
Resolved by 214618d105e2817385288f674ee26bd7b2ec28a1
