### ISSUE TITLE
Streamers overlay (website)

### ISSUE THREAD

**Issue by MatisseBE** [maiuswong/simaware-express#9]
If there's too many streamers at once, the streamers' overlay from the website itself isn't scrollable, so you can't see everyone. 

I'm talking about the list shown below:
![image](https://user-images.githubusercontent.com/51272243/157042429-3095d153-f131-4f7a-9741-dba71ad73bfd.png)

_Originally posted by @MatisseBE in https://github.com/maiuswong/simaware-express/issues/8#issuecomment-1060683075_

**Comment by Lulsgate** [comment]
Would be a cool feature to be able to hide this section.

**Comment by maiuswong** [comment]
New design for streamers in the bottom left hand side as of 675c6c3.
