### ISSUE TITLE
Display of virtual airlines

### ISSUE THREAD

**Issue by medibasti05** [maiuswong/simaware-express#96]
Hello dear SimAware team,

Unfortunately, virtual airlines are not displayed by name, which is a great pity because virtual airlines are also part of VATSIM.

We have already tried to find a contact person, but cannot find or reach anyone. 

It would be nice if we could have a contact person.

**Comment by maiuswong** [comment]
We are not adding any more to the list of airlines.  The sheer number of requests received over the past month has been overwhelming.

I will not revisit this decision.
